spring:
  application:
    name: yanyu-ai-code
  # mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yanyu_ai_code
    username: root
    password: 20040301

server:
  port: 8123
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.ityanyu.yanyuaicode.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

